name: 'insurance_analytics'
version: '1.0.0'
config-version: 2

# This tells dbt to use the profiles.yml (we will use DuckDB)
profile: 'insurance_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
models:
  insurance_analytics:
    # This ensures everything in the models folder is materialized as a table
    materialized: table